export const createBookType = 'book/create'
export const getBookType = 'book/get'
export const updateBookType = 'book/update'
export const deleteBookType = 'book/delete'
export const getHomeBookType = 'book/getHome'
